name: Cypress Tests

on:
  push:
    branches:
      - stage

env:
  PLATFORMSH_CLI_TOKEN: ${{ secrets.PLATFORMSH_CLI_TOKEN }}

jobs:
  cypress:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install Psh CLI.
      - name: Install Psh CLI
        run: |
          curl -sS https://platform.sh/cli/installer | php

      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
        uses: cypress-io/github-action@v5
        with:
          build: npm install
          start: |
            npm run cypress --browser chrome -- --spec ./cypress/e2e/figmaTests/button.cy.js

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: |
            cypress/screenshots
            cypress/videos
            cypress-visual-screenshots
          if-no-files-found: warn
